config/routes.rb
Roqbox::Application.routes.draw do

  devise_for :users
  get "users/profile"

  post '/' => 'home#create'

  root :to => "home#index"

  get 'thecoolband' => 'home#thecoolband'
  get 'theradband' => 'home#theradband'
  get 'sweetband' => 'home#sweetband'

  match 'user/:id' => 'users#profile', :as => :user

  get 'profiles' => 'profiles#index'

  resources :profiles, :only => [ :show ], :path => ''
  resources :profiles do
    resources :boxes
  end

end

app/models/box.rb
class Box < ActiveRecord::Base
  belongs_to :profile
  attr_accessible :text
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  has_many :boxes
  attr_accessible :slug

  validates :slug,
  	:presence => true,
  	:format => { :with => /\A[-0-9a-z_]*\Z/i },
  	:uniqueness => true

  has_and_belongs_to_many :users

  def to_param
  	return slug
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username, :login
  # attr_accessible :title, :body


  has_and_belongs_to_many :profiles

  def created_profiles
  	Profile.where("creator = ?", id)
  end



  def login=(login)
    @login = login
  end

  def login
    @login || self.username || self.email
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/boxes_controller.rb
class BoxesController < ApplicationController

	# Show the form to the user
	def new
		@profile = Profile.find_by_slug!(params[:profile_id])
		@box = @profile.boxes.new
	end


	def create
		# Find our profile again
		@profile = Profile.find_by_slug!(params[:profile_id])

		# Make a new box object (long way)
		@box = @profile.boxes.new
		@box.text = params[:box][:text]
		@box.save

		# Make a new box object (short way):
		# @box = @profile.boxes.create(params[:box])

		# Redirect to the path of the profile after creating a box
		redirect_to profile_path(@profile)
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index

		@profile = Profile.new
		if signed_in?
			@user = current_user

			@profiles = Profile.where("creator = ?", @user.id)
		end

	end

	

	

	#def thecoolband
		# Don't need anything here.
	#end

	def theradband
		logger.info "Hello there"
		# Don't need anything right here.
	end

	def sweetband
		logger.info "Terminal/server output test"
	end

	def layout_designer
		logger.info "this is where one would expect a terminal output"
	end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

	def index
		@profiles = Profile.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @profiles }
    end
  end

  def new
  	@user = current_user
    @profile = @user.profiles.build(params[:profile])
    @profile.creator = @user

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @profile }
    end
  end

	def create
		logger.info "Create action in home_controller was triggered here"
		logger.info params.inspect
		logger.info "----- params[:slug] = " + params[:slug] + "-----\n\n"
		@profile = Profile.new

		@profile.creator = current_user.id

		logger.info "--- @profile.inspect: " + @profile.inspect + " ----\n\n"
		@profile.slug = params[:slug]
		logger.info "--- @profile.inspect: " + @profile.inspect + " ----\n\n"

		@profile.users << current_user

		if @profile.save
			logger.info "--- @profile.inspect: " + @profile.inspect + " ----\n\n"
			redirect_to profile_path(@profile)
		else
      format.html { render action: "new" }
      format.json { render json: @profiles.errors, status: :unprocessable_entity }
		end
	end

	def show
		logger.info "--- Hey! params[:id]: " + params[:id] + " -----\n\n"
		@slug = params[:id]
		@profile = Profile.find_by_slug!(@slug)

	end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def profile
  	@fuckyou = 'Hey, fuck you, guy.'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boxes_helper.rb
module BoxesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/boxes/new.html.erb
<div class="hero-unit">
	<h1>create a new box.</h1>
	<%= form_for [@profile, @box] do |f| %>
		 <%= f.text_area :text, :rows => 5, :class => "span7" %>
  		 <%= f.submit "Create" %>
	<% end %>
</div>

app/views/home/index.html.erb
<% if user_signed_in? %>

	<%= render 'users/dashboard' %>

<% else %>

<div class="hero-unit">
	<h1>Roqbox is a music service for motherfuckers.</h1>
	<p>
			<%= link_to "Fuck you", new_user_registration_path, class: "btn btn-primary btn-large" %>
		</p>
</div>

<% end %>

app/views/home/layoutdesigner.html.erb
<br><br><br><br>
layout designer 0.0

app/views/home/sweetband.html.erb
<div class="row">
	<div class="span8 offset2">
		<div class="thumbnail" style="text-align:center">
			<h1>Sweet Band</h1>
		</div>
	</div>
</div>

<div class="row">
	<div class="span6">
		<div class="thumbnail">
			<img src="http://placehold.it/1250x1250">
		</div>
	</div>
	<div class="span6">
		<div class="row">
			<div class="span6 thumbnail">
				<p>Sweet Band is a rockin bluegrass/electro outfit from Reginald, WY. Featuring Todd Langley on the eBanjo and Miriam Gorblsey on the washboard, you're sure to enjoy their eclectic mix of stuff.</p>
			</div>
		</div>
		<div class="row">
			<div class="span6 thumbnail">
				<p>UPCOMING SHOWS<br><br>May 3 - Bob's BBQ<br>May 6 - The Hornwell</p>
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="span8 offset2">
		<div class="thumbnail" style="text-align:center">
			<h1>mp3 player goes here</h1>
		</div>
	</div>
</div>

app/views/home/thecoolband.html.erb
<b>thecoolband</b> page

app/views/home/theradband.html.erb
<h1>The Rad Band</h1>

<ul class="thumbnails">
  <li class="span7">
    <div class="thumbnail">
      <h3>Thumbnail label</h3>
      <p>Thumbnail caption...</p>
    </div>
  </li>
  <li class="span3">
  	<div class="thumbnail">
  		<h2>test</h2>
  	</div>
  </li>
  <li class="span5">
  	<div class="thumbnail">
  		<p>Ipsum norum eteriertr</p>
  	</div>
  </li>
 </ul>

app/views/layouts/_nav.html.erb
<div id="nav_bar" style="position: fixed; z-index: 2; width: 100%; height: 50px;">
	<ul class="nav nav-pills">
<!-- nav pills to come -->
	</ul>

	
	<a href="/">
		<div id="roqbox_container_r">
			<div id="roqbox_r_1"></div>
			<div id="roqbox_r_2" class="arrow-left"></div>
			<div id="roqbox_r_3" class="arrow-left"></div>
			<div id="roqbox_r_4"></div>
			<div id="roqbox_r_5"></div>
		</div> <!-- test123 -->
	</a>

	<div style="position: absolute; top: 15px; right: 15px;">
		<% if user_signed_in? %>

		<span class="nav_text">
			<%= link_to "Profile", current_user %>
		</span>

		<span style="color:#999999;">|</span>

		<span class="nav_text">
			<%= link_to "Logout", destroy_user_session_path, method: :delete %>
		</span>

		<% else %>

		<!--<a href="/">home</a>
		<p>test</p>-->

		<span class="nav_text">
			<%= link_to "Signup", new_user_registration_path %>
		</span>

		<span style="color:#999999;">|</span>

		<span class="nav_text">
			<%= link_to "Login", new_user_session_path %>
		</span>
		
		<% end %>
	</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Roqbox</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/nav' %>

<div class="container" id="main_body">
	<%= yield %>
</div>

</body>
</html>

app/views/profiles/index.html.erb
<h1>Listing profiles</h1>

<table>
  <tr>
    <th>Slug</th>
    <th>Creator</th>
    <th></th><th></th><th></th>
  </tr>

<% @profiles.each do |profile| %>
  <tr>
    <td><%= profile.slug %></td>
    <td><%= profile.creator %></td>
    <td><%= link_to 'Show', profile %></td>
    <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
    <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>Hello, world</h1>

app/views/profiles/show.html.erb
<div class="row">
	<div class="span2 offset10">
		<a href="<%= new_profile_box_path(@profile) %>">Add new box</a>
	</div>
</div>

<div class="row">
	<div class="span8 offset2">
		<div class="thumbnail" style="text-align:center">
			<h1><%= @slug %></h1>
		</div>
	</div>
</div>


<% @profile.boxes.each do |box| %>
	<div class="row">
		<div class="span8 offset2">
			<div class="thumbnail" style="text-align:center">
				<p><%= box.text %></p>
			</div>
		</div>
	</div>
<% end %>

app/views/shared/_dashboard_profile.html.erb
<h3><%= link_to(profile.slug, profile) %></h3>

app/views/users/_dashboard.html.erb
<div class="hero-unit">
	<h1>Hey, <%= @user.email %></h1>
	<%= form_for @profile do %>
		<p>roqbox.net/<%= text_field_tag(:slug,"",:class=>"span4") %></p>
		<p><%= submit_tag("create new profile",:class=>"btn btn-primary") %></p>
	<% end %>
</div>

<div class="tool_box">
	<h2>Profiles you've created</h2>
	<% @user.created_profiles.each do |created_profile| %>
	<%= render :partial => 'shared/dashboard_profile', :object => created_profile, :as => :profile %>
	<% end %>
</div>

app/views/users/profile.html.erb
<h1>Profile View!</h1>
<p>Find me in app/views/users/profile.html.erb</p>
<p><%= @fuckyou %></p>